


FROM decentration/pop-art:v0.9.12 as builder 

FROM debian:buster-slim
LABEL description="This is the 2nd stage: a very small image where we copy the polkadot binary."
ARG PROFILE=release
COPY --from=builder usr/local/bin /usr/local/bin
RUN apt update && apt install -y ca-certificates
COPY ./specs/ /specs/
RUN useradd -m -u 1000 -U -s /bin/sh -d /polkadot polkadot && \
	mkdir -p /polkadot/.local/share && \
	mkdir /data && \
	chown -R polkadot:polkadot /data && \
	ln -s /data /polkadot/.local/share/polkadot && \
	rm -rf /usr/bin /usr/sbin

USER polkadot
EXPOSE 30333-30343 9933-9960 8080 300
VOLUME ["/data"]

CMD ["/usr/local/bin/polkadot"]